name: workbench
version: 0.0.1
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A workspace to host pub packages
homepage: https://github.com/flutter/engine/tree/master/sky/packages/workbench
dependencies:
  flutter: any
  sky_tools: any
dependency_overrides:
  material_design_icons:
    path: ../material_design_icons
  flutter:
    path: ../sky
environment:
  sdk: '>=1.8.0 <2.0.0'
