name: workbench
version: 0.0.1
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A workspace to host pub packages
homepage: https://github.com/flutter/engine/tree/master/sky/packages/workbench
dependencies:
  flutter: ">=0.0.3 <0.1.0"
  sky_tools: ">=0.0.26"
  cipher: any
  asn1lib: any
dependency_overrides:
  material_design_icons:
    path: ../material_design_icons
  flutter:
    path: ../sky
environment:
  sdk: '>=1.8.0 <2.0.0'
