name: workbench
version: 0.0.1
author: Chromium Authors <sky-dev@googlegroups.com>
description: A workspace to host pub packages
homepage: https://github.com/domokit/sky_engine/tree/master/sky/packages/workbench
dependencies:
  sky: any
  sky_tools: any
dependency_overrides:
  material_design_icons:
    path: ../material_design_icons
  sky:
    path: ../sky
environment:
  sdk: '>=1.8.0 <2.0.0'
