name: asteroids
dependencies:
  flutter: ">=0.0.3 <0.1.0"
  sky_tools: any
  flutter_sprites: any
  box2d: any
dependency_overrides:
  material_design_icons:
    path: ../../sky/packages/material_design_icons
  flutter:
    path: ../../sky/packages/sky
  flutter_sprites:
    path: ../../skysprites
