name: stocks
author: Chromium Authors <sky-dev@googlegroups.com>
description: A demo application using Sky that shows stock data
homepage: https://github.com/domokit/mojo/tree/master/sky/examples/stocks-fn
version: 0.0.1
dependencies:
  sky: '>=0.0.1 <1.0.0'
