name: sky_unit_tests
dependencies:
  flutter: ">=0.0.3 <0.1.0"
  sky_tools: any
  test: any
  quiver: any
dependency_overrides:
  material_design_icons:
    path: ../packages/material_design_icons
  flutter:
    path: ../packages/sky
