author: Chromium Authors <mojo-dev@googlegroups.com>
dependencies:
  mojo: '>=0.2.0 <0.3.0'
  mojom: '>=0.2.0 <0.3.0'
description: Generated bindings for mojo services
homepage: https://github.com/domokit/mojo
name: mojo_services
version: 0.2.1
