name: sky_updater
version: 0.0.1
author: Flutter Authors <flutter-dev@googlegroups.com>
description: The autoupdater for flutter
homepage: http://flutter.io
dependencies:
  mojo: ^0.0.21
environment:
  sdk: '>=1.12.0 <2.0.0'
