name: sky_services
version: 0.0.31
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Mojom interfaces associated with Flutter
homepage: http://flutter.io
dependencies:
  mojo: '>=0.1.0 <0.2.0'
environment:
  sdk: '>=1.8.0 <2.0.0'
