name: sky_services
version: 0.0.25
author: Chromium Authors <sky-dev@googlegroups.com>
description: Mojom interfaces associated with Flutter
homepage: http://flutter.io
dependencies:
  mojo: ^0.0.21
environment:
  sdk: '>=1.8.0 <2.0.0'
