name: skysprites
description: A sprite toolkit built on top of Sky.
version: 0.0.1
author: Chromium Authors <sky-dev@googlegroups.com>
homepage: https://github.com/domokit/sky_engine/tree/master/sky/packages/sky
dependencies:
  sky: ">=0.0.36 < 0.1.0"
  sky_tools: ">=0.0.10 < 0.1.0"
dependency_overrides:
  sky:
    path: ../sky/packages/sky
