name: flutter_sprites
description: A sprite toolkit built on top of Flutter
version: 0.0.7
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: http://flutter.io
dependencies:
  flutter: ">=0.0.10 <0.1.0"
  sky_tools: ">=0.0.20 <0.1.0"
  box2d: ">=0.2.0 <0.3.0"
