name: flutter_sprites
description: A sprite toolkit built on top of Flutter
version: 0.0.13
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: http://flutter.io
dependencies:
  flutter: 
    '0.0.16'
  box2d: ">=0.2.0 <0.3.0"
