name: skysprites
description: A sprite toolkit built on top of Flutter
version: 0.0.1
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: http://flutter.io
dependencies:
  sky: ">=0.0.36 < 0.1.0"
  sky_tools: ">=0.0.10 < 0.1.0"
dependency_overrides:
  sky:
    path: ../sky/packages/sky
