author: Chromium Authors <sky-dev@googlegroups.com>
dependencies:
  cassowary: '^0.1.7'
  mojo_services: '^0.0.15'
  mojo: '^0.0.17'
  mojom: '^0.0.17'
  newton: '^0.1.0'
  vector_math: '^1.4.3'
description: Dart files to support executing inside Sky.
homepage: https://github.com/domokit/mojo/tree/master/sky
environment:
  sdk: ">=1.8.0 <2.0.0"
name: sky
version: 0.0.17
