name: fitness
dependencies:
  sky: any
  sky_tools: any
  playfair: "^0.0.5"
  path: "^1.3.6"
dependency_overrides:
  material_design_icons:
    path: ../../sky/packages/material_design_icons
  sky:
    path: ../../sky/packages/sky
