name: fitness
dependencies:
  flutter: any
  sky_tools: any
  playfair: ^0.0.9
  path: ^1.3.6
dependency_overrides:
  material_design_icons:
    path: ../../sky/packages/material_design_icons
  flutter:
    path: ../../sky/packages/sky
