author: Chromium Authors <sky-dev@googlegroups.com>
dependencies:
  archive: '>=1.0.20 <2.0.0'
  args: '>=0.13.0 <1.0.0'
  yaml: '>=2.1.3 <3.0.0'
description: Developer tool for packaging Sky applications
homepage: https://github.com/domokit/sky_engine/tree/master/sky/tools/skyx
name: skyx
version: 0.0.3
